# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 494d4f2e5cede0e5747303817aac75f16dd59180801e9c0466ac9bf5794b8878a0d656002d40a58c9e405845d7eb41f4935eb012f20d2af944c7b886ab0346ba

test:
  secret_key_base: 61850625bc10087fc46a51710b35961de8ff533e3e9671400475e8a0ecded19ec4d420a332faba3a38005b82e4d438fbabb72741540ca01822818f6584f7a4c0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
